### ISSUE TITLE
Type 'DecoderBufferCallback' not found and 'Uint8List' not found.

### ISSUE THREAD

**Issue by tebalink** [rafaelsetragni/awesome_notifications_fcm#13]
Running Gradle task 'assembleDebug'...
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:40:26: Error: Type 'DecoderBufferCallback' not found.
      ResourceImage key, DecoderBufferCallback decode) {
                         ^^^^^^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:48:26: Error: Type 'DecoderBufferCallback' not found.
      ResourceImage key, DecoderBufferCallback decode) async {
                         ^^^^^^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/awesome_notifications_method_channel.dart:186:10: Error: Type 'Uint8List' not found.
  Future<Uint8List?> getDrawableData(String drawablePath) async {
         ^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:21:7: Error: The non-abstract class 'ResourceImage' is missing implementations for these members:
 - ImageProvider.load
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ResourceImage extends ImageProvider<ResourceImage> {
      ^^^^^^^^^^^^^
../../../development/flutter/packages/flutter/lib/src/painting/image_provider.dart:567:24: Context: 'ImageProvider.load' is defined here.
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:40:26: Error: 'DecoderBufferCallback' isn't a type.
      ResourceImage key, DecoderBufferCallback decode) {
                         ^^^^^^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:48:26: Error: 'DecoderBufferCallback' isn't a type.
      ResourceImage key, DecoderBufferCallback decode) async {
                         ^^^^^^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:50:5: Error: 'Uint8List' isn't a type.
    Uint8List? bytes =
    ^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/back_button_interceptor-5.0.2/lib/src/back_button_interceptor.dart:29:74: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
  static Future<void> Function() handlePopRouteFunction = WidgetsBinding.instance!.handlePopRoute;
                                                                         ^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/back_button_interceptor-5.0.2/lib/src/back_button_interceptor.dart:32:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.handlePushRoute as Future<void> Function(String?);
                     ^

FAILURE: Build failed with an exception.

* Where:

[✓] Flutter (Channel stable, 3.0.0, on macOS 12.6 21G115 darwin-arm (Rosetta), locale en-EG)
    • Flutter version 3.0.0 at /Users/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (6 months ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3345.108

[✓] Connected device (2 available)
    • SM G610F (mobile) • 5203fd5afa51b33f • android-arm  • Android 8.1.0 (API 27)
    • macOS (desktop)   • macos            • darwin-arm64 • macOS 12.6 21G115 darwin-arm (Rosetta)
    ! Error: sayed is not connected. Xcode will continue when sayed is connected and unlocked. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by toblinkz** [comment]
I'm also having the same issue any solution please

**Comment by rafaelsetragni** [comment]
You need to upgrade your flutter version with `flutter upgrade`
