### ISSUE TITLE
Could not find module 'awesome_notifications_fcm' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by appinteractive** [rafaelsetragni/awesome_notifications_fcm#14]
## **1 - Describe the bug**
I get the following warning in Xcode, could that be an issue? As far as I can tell, debug does work for now. If it is not an issue, there should maybe be a note in the README.

```sh
Could not find module 'awesome_notifications_fcm' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/Greg/Library/Developer/Xcode/DerivedData/Runner-ggvlrwomhxdzqybvllkuxzmqawmi/Index.noindex/Build/Products/Debug-iphonesimulator/awesome_notifications_fcm/awesome_notifications_fcm.framework/Modules/awesome_notifications_fcm.swiftmodule
```

## **3 - How To Reproduce the Error**
Follow the instructions in the README on a M1 Mac and see the issue in Xcode

## **4 - Expected behavior**
Should also build on `arm64` (mac M1 & M2)

## **5 - Screenshots**
<img width="989" alt="grafik" src="https://user-images.githubusercontent.com/432828/202194360-dc4d449d-0bfa-4a43-bb59-f136c878716d.png">

**Comment by rafaelsetragni** [comment]
The plugin was not copied into MyAppServiceExtension. This step happens after you modify your podfile and run `pod install`.
You can also check the framework file containing all architectures in the pod IosAwnFcmDist in your Pod sub projects.

**Comment by appinteractive** [comment]
Seems to be fine now, thanks.

<img width="260" alt="grafik" src="https://user-images.githubusercontent.com/432828/202400132-52ba9fcf-c553-493b-8f4b-60c5eb383caa.png">

**Comment by scopendo** [comment]
Thank you for replying @appinteractive -- we've tried those options many times 😵‍💫

I'll open a new issue.

**Comment by appinteractive** [comment]
Just checked my commit history from back then, but it was a huge refactoring and I do not see anything noteworthy beside that I kicked iPad support and redo the whole awesome_notification_fcm tutorial. Hell I even made a new documentation side as a means to get my head around (which got rejected 🤷‍♂️ )

https://awesome-notification-docs.vercel.app/
https://github.com/rafaelsetragni/awesome_notifications/pull/655
