### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by yashhema** [rafaelsetragni/awesome_notifications_fcm#2]
Flutter doctor :

doctor --verbose
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.1098], locale en-US)
    • Flutter version 3.0.5 at D:\SMSBApp\.fvm\flutter_sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\bhard\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\bhard\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.1098]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 106.0.1370.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

On Compiling - getting below error

/C:/Users/bhard/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/awesome_notifications-0.7.2/lib/src/utils/resource_image_provider.dart:40:26: Error: 'DecoderBufferCallback' isn't a type.
      ResourceImage key, DecoderBufferCallback decode) {
                         ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/bhard/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/awesome_notifications-0.7.2/lib/src/utils/resource_image_provider.dart:48:26: Error: 'DecoderBufferCallback' isn't a type.
      ResourceImage key, DecoderBufferCallback decode) async {
                         ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/bhard/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/awesome_notifications-0.7.2/lib/src/utils/resource_image_provider.dart:50:5: Error: 'Uint8List' isn't a type.
    Uint8List? bytes =
    ^^^^^^^^^

**Comment by rafaelsetragni** [comment]
You need to update your Flutter/Dart SDK version.

**Comment by yashhema** [comment]
Thanks its sorted , moved to flutter 3.3.0

**Comment by iabdousd** [comment]
@rafaelsetragni, you can close this I guess.

**Comment by rafaelsetragni** [comment]
Thanks!
