### ISSUE TITLE
Tap notification not working when app terminated for ios

### ISSUE THREAD

**Issue by dangminhchau1994** [rafaelsetragni/awesome_notifications_fcm#20]
In foreground and background mode when I tap in notification it will show a dialog that is logic in my app, but when I tap into notification when app is terminated and open app it not show dialog, please help me

**Comment by rafaelsetragni** [comment]
You need to debug your app to detect if you get the notification action event and what happens after it.

**Comment by dangminhchau1994** [comment]
android is working fine, but ios not run my logic it just same logic and same flow but it working on android not ios
