### ISSUE TITLE
`onFcmSilentDataHandle` is never called on iOS on example app.

### ISSUE THREAD

**Issue by PedroMGomes** [rafaelsetragni/awesome_notifications_fcm#21]
##  Describe the bug

Using the [example](https://pub.dev/packages/awesome_notifications_fcm/example) app, the `onFcmSilentDataHandle` is never called **on iOS** , for data-only/silent notifications. No logs are displayed on the terminal after the notification is sent. The FCM and Native (APNs) tokens are successfully generated and notification permissions are granted on my testing device. “Normal” notifications (with the `notification` payload) are always delivered. 

Not sure if this is a bug or just some miss configuration on my part, so I’ll be providing a list of what I did below. Thanks in advance.

## Provide us as much information as possible

1. Created a new project with `flutter create`.
2. Added the following dependencies:
```yaml
awesome_notifications: ^0.7.4+1
awesome_notifications_fcm: ^0.7.4+1
firebase_core: ^2.4.1
```
3. Ran `pod install`.
4. From the Apple Developer Account, I’ve created an App Key (with APNs enabled) and an App ID with **App Groups** and **Push Notifications** enabled. Clicking on the *Configure* button, next to **Push Notifications**, opens the SSL certificates dialog/modal to add a Development and Production SSL Certificate. I have none, presuming the App Key replaces the use of Certificates in this scenario.
5. Configured a new Firebase project via [console](https://console.firebase.google.com/). Created a new project and enabled both Firebase Cloud Messaging API (V1) and Cloud Messaging API (Legacy). For iOS, I uploaded the APNs Auth Key that I generated on step 4. Finally, I added Firebase configuration files to the Flutter project.
6. On Xcode, enabled **Background Modes** (Background Fetch and Remote Notifications), **Push Notifications** and **App Groups** in the *Signing & Capabilities* section for the Runner target. In the *Build Settings* section:
	1. Build Libraries for Distribution: NO
	2. Require Only App-Extension-Safe API: NO
	3. iOS Deployment Target: iOS 11.0
7. Configured Awesome Notifications FCM for iOS exactly as described [here](https://pub.dev/packages/awesome_notifications_fcm#-ios-configuration). New Notification Service Extension target, gave it a custom name, added the pod mod at the bottom of the `Podfile` replacing the name where needed (2x), edited the `NotificationService.swift`, enabled **App Groups** as well, and, on the *Build Settings* section:
	1. Build Libraries for Distribution: NO
	2. Require Only App-Extension-Safe API: YES
	3. iOS Deployment Target: iOS 11.0
8. Ran the app to get the App Group value from the Awesome notifications log, and added that value to both targets on Xcode.
9. `flutter clean` followed by `flutter pub get`.
10. The app builds successfully, everything works as expected besides silent notifications.

### Environment
- iPhone SE - iOS 16.2
- M1 - Ventura 13.1
- Xcode 14.2

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```
### FCM Payloads used:
- V1:
```json
{
	"message": {
		"token": "{{ _.push.firebase_ios_token }}",
		"data": {
			"title": "Data notification title",
			"body": "Data notification body",
		},
		"apns": {
			"payload": {
				"aps": {
					"content-available": 1,
				}
			}
		}
	}
}
```
- Legacy: 
```json
{
	"to" : "{{ _.push.firebase_ios_token }}",
	"content_available": true,
	"data" : {
		"title": "Legacy Silent Notification",
		"body": "Legacy Silent Notification",
	}
}
```

**Comment by rafaelsetragni** [comment]
Try to use the "Console.app" on MacOS to read the devices log and get the error when you send your silent push notification.
Just to remember, `onFcmSilentDataHandle` must be static or global. You can't use lambda functions to listen notification events.

**Comment by san1109** [comment]
same issue but on normal push notification posted the issue as another bug. @rafaelsetragni can you help me with this as soon as possible. Everything works fine in android but the issue is only in ios.

**Comment by rafaelsetragni** [comment]
Guys, i need your logs to understand what is going on. And to get the logs while the app is terminated, you need to use the "Console.app".

Remember that not all resources are available while your app is in terminated state, and you have a time limit to execute the tasks.

**Comment by jerdesk** [comment]
In your "Info.plist" have you tried to set the "FirebaseAppDelegateProxyEnabled" to false ?

I solved mine with this configuration.

**Comment by rafaelsetragni** [comment]
Also this push content is not correct. Check the postman examples at the documentation. There are many validated examples of how to send notifications, including silent ones.
