### ISSUE TITLE
issue when adding notification service extention 

### ISSUE THREAD

**Issue by Nader2004** [rafaelsetragni/awesome_notifications_fcm#24]
Hello,

I was following the instructions to add awesome notifications to iOS according to the documentation, but there seem to be an issue when adding my created notification service extension code to the Podfile. I get the ouput of this error:

```
[!] Invalid `Podfile` file: You need to create a Notification Service Extension to properly use awesome_notifications_fcm
.

 #  from /Users/naderkhaled/Looper/ios/Podfile:56
 #  -------------------------------------------
 #  end
 >  update_awesome_fcm_service_target('LooperNotificationsServiceExtention', File.dirname(File.realpath(__FILE__)), flutter_root)
 #  ################  Awesome Notifications FCM pod mod  ###################

```

Thing is I have already created a target with a Notification Serivce Extention in Xcode, but for some reason it still shows me this error. 

Am I missing something? 
Thanks!

**Comment by ektapadaliya** [comment]
@Nader2004 any workaround ?

**Comment by rafaelsetragni** [comment]
Well, the error is self explanatory. You need to add a NSE (Notification Service Extension) to use 'awesome_notifications_fcm', and your NSE name need to be paste inside the pod modification, as described in the `Getting started` topic.

If you're getting this error, that means your NSE was not found by the awesome's pod script.

**Comment by Nader2004** [comment]
Hello @rafaelsetragni , I am sorry for the late reply. Thanks for clarifying the issue but i have dismissed using notification extension as I no longer need it. Anyway thank you for the help!
