### ISSUE TITLE
Where do I buy the license?

### ISSUE THREAD

**Issue by matheus85** [rafaelsetragni/awesome_notifications_fcm#25]
Where do I buy the license?

Site off, discord off........

**Comment by steveneal** [comment]
Me too. Discord is down.

**Comment by rafaelsetragni** [comment]
The web portal where you manage your applications, as well as the FCM documentation, are in the final stages of construction. So, for now, if you want to buy a license, you have these three options:

Paypal:
https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&business=payments%40carda%2eme&lc=US&item_name=Awesome%20Notifications%20FCM%20%2d%20License%20Key&item_number=awn%2dfcm%2dlicense&amount=9%2e99&currency_cod

Paypal donations:
rafaelsetra@gmail.com

Buy me a coffee:
https://www.buymeacoffee.com/rafaelsetragni

Also i've fixed the discord link. To access our discord community, please go to:
https://discord.awesome-notifications.carda.me
