### ISSUE TITLE
awesome notification onnotificationcreated method is not triggered in ios

### ISSUE THREAD

**Issue by san1109** [rafaelsetragni/awesome_notifications_fcm#26]
I followed everything said in this package but couldn't handle the notification received but when I click on it the onreceived action is triggered. my
 payload:{
    "message": {
        "token": "{token}",
        "notification": {
            "title": "{data1}",
            "body": "{body}"
        },
        "data": {
           //data entered here
        },
        "apns": {
            "headers": {
                "apns-push-type": "alert",
                "apns-priority": "5"
            },
            "payload": {
                "aps": {
                    "content-available":1,
                    "mutable-content": 1
                }
            }
        }
    }
}

**Comment by san1109** [comment]
please help me with this as soon as possible my team is struck with this and the release is being delayed.

**Comment by rafaelsetragni** [comment]
"content-available":1,
"mutable-content": 1

You did not followed the examples in the Awesome Notifications FCM documentation. You should never use `content-available` and `mutable-content` at same time. They mean different things.
