### ISSUE TITLE
Crash after sending notification with content_available on ios in release

### ISSUE THREAD

**Issue by radroot1** [rafaelsetragni/awesome_notifications_fcm#27]
fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0 22A380 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

awesome_notifications: 0.7.4+1
awesome_notifications_fcm: 0.7.4+1

Crashed after sending notification with content_available on ios in release.
On debug, profile build everything is fine

[stacktrace.txt](https://github.com/rafaelsetragni/awesome_notifications_fcm/files/10543986/stacktrace.txt)
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/38936506/215698688-b557f5d6-de4c-4d8a-95d6-b4fc97ed0d8d.png">
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/38936506/215698687-fe1c9ecb-e9db-4d04-93cd-fb483aac4609.png">

**Comment by rafaelsetragni** [comment]
This is really bizarre, since the code is using null safety and the destroyContext must be called to shut down the flutter engine.
Try to capture the device log using the app in MacOS called "Console.app"

**Comment by radroot1** [comment]
I found bug in my own code.
I was sending custom object through SendPort.
```
      final SendPort? uiSendPort = IsolateNameServer.lookupPortByName(_bgPortName);
      uiSendPort?.send(notification);
```

Although it is my own fault, this is really impossible to debug. There wasn't anything discernible except SEGFAULT 🤯 
Closing the issue, sorry for the fuss
