### ISSUE TITLE
Notifications are not showing

### ISSUE THREAD

**Issue by BluffChief0** [rafaelsetragni/awesome_notifications_fcm#28]
I try to migrate from firebase_messaging to awesome_notifications_fcm. I've repleced all firebase methods by its equivalents on Awesome Notifications and Awesome Notifications FCM. And when i send notification from my backend server I see the following error:
D/Android: [Awesome Notifications]( 4784): A new Awesome FCM service has started (AwesomeFcmService:46)
D/Android: [Awesome Notifications]( 4784): received a new fcm push (id: 0:1675167210056587%939c6b1e939c6b1e) (AwesomeFcmService:134)
W/Android: [Awesome Notifications]( 4784): Channel model 'alerts' was not found (ChannelManager:88)
E/Android: [Awesome Notifications]( 4784): Notification channel 'alerts' does not exist. (NotificationContentModel:58)
W/System.err( 4784): me.carda.awesome_notifications.core.exceptions.AwesomeNotificationsException: Notification channel 'alerts' does not exist.
W/System.err( 4784):    at me.carda.awesome_notifications.core.exceptions.ExceptionFactory.createNewAwesomeException(ExceptionFactory.java:31)
W/System.err( 4784):    at me.carda.awesome_notifications.core.models.NotificationContentModel.validate(NotificationContentModel.java:256)
W/System.err( 4784):    at me.carda.awesome_notifications.core.models.NotificationModel.validate(NotificationModel.java:137)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.interpreters.FcmInterpreter.deliveryAwesomeNotification(FcmInterpreter.java:143)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.interpreters.FcmInterpreter.processPushContent(FcmInterpreter.java:100)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.interpreters.FcmInterpreter.executeRemoteInstructions(FcmInterpreter.java:79)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.services.AwesomeFcmService.passMessageIntentToSdk(AwesomeFcmService.java:174)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.services.AwesomeFcmService.handleMessageIntent(AwesomeFcmService.java:137)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.services.AwesomeFcmService.handleIntent(AwesomeFcmService.java:70)
W/System.err( 4784):    at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(EnhancedIntentService.java:78)
W/System.err( 4784):    at com.google.firebase.messaging.-$$Lambda$EnhancedIntentService$NSk2h75eWhBOI4TsAFgvvtv1g9o.run(Unknown Source:6)
W/System.err( 4784):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/System.err( 4784):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/System.err( 4784):    at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
W/System.err( 4784):    at java.lang.Thread.run(Thread.java:1012)

And when I try to get notification from chat, which was connected to firebase_messaging I see this error:
D/Android: [Awesome Notifications]( 4784): received a new fcm push (id: 0:1675167120696520%939c6b1e939c6b1e) (AwesomeFcmService:134)
E/Android: [Awesome Notifications]( 4784): Index: 0, Size: 0 (FcmInterpreter:58)
W/System.err( 4784): me.carda.awesome_notifications.core.exceptions.AwesomeNotificationsException: Index: 0, Size: 0
W/System.err( 4784):    at java.util.ArrayList.get(ArrayList.java:437)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.builders.FcmNotificationBuilder.getFirstAvailableChannelKey(FcmNotificationBuilder.java:149)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.builders.FcmNotificationBuilder.receiveStandardNotificationContent(FcmNotificationBuilder.java:131)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.builders.FcmNotificationBuilder.buildNotificationFromExtras(FcmNotificationBuilder.java:79)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.interpreters.FcmInterpreter.deliveryAwesomeNotification(FcmInterpreter.java:134)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.interpreters.FcmInterpreter.processPushContent(FcmInterpreter.java:100)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.interpreters.FcmInterpreter.executeRemoteInstructions(FcmInterpreter.java:79)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.services.AwesomeFcmService.passMessageIntentToSdk(AwesomeFcmService.java:174)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.services.AwesomeFcmService.handleMessageIntent(AwesomeFcmService.java:137)
W/System.err( 4784):    at me.carda.awesome_notifications_fcm.core.services.AwesomeFcmService.handleIntent(AwesomeFcmService.java:70)
W/System.err( 4784):    at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(EnhancedIntentService.java:78)
W/System.err( 4784):    at com.google.firebase.messaging.-$$Lambda$EnhancedIntentService$NSk2h75eWhBOI4TsAFgvvtv1g9o.run(Unknown Source:6)
W/System.err( 4784):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/System.err( 4784):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/System.err( 4784):    at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
W/System.err( 4784):    at java.lang.Thread.run(Thread.java:1012)

I didn't find any solution in internet, maybe here can anyone help me

**Comment by rafaelsetragni** [comment]
You're trying to use a notification channel that does not exists in your app. The example app creates and uses a notification channel called 'alerts', and you must to do the same to use this channel.

**Comment by BluffChief0** [comment]
Yes, that's helped. Thx a lot:)

**Comment by guyluz11** [comment]
> Yes, that's helped. Thx a lot:)

If it working for you now please close the issue.

Thanks
