### ISSUE TITLE
mySilentDataHandle not working 

### ISSUE THREAD

**Issue by jerdesk** [rafaelsetragni/awesome_notifications_fcm#29]
Hi,

I'm stucked with the usage of the plugin SharedPreferences with inside the method "mySilentDataHandle" 

I get this error : 
flutter: PlatformException(channel-error, Unable to establish connection on channel., null, null)

My code is : 
`@pragma("vm:entry-point")
  static Future<void> mySilentDataHandle(FcmSilentData silentData) async {
    WidgetsFlutterBinding.ensureInitialized();
    DartPluginRegistrant.ensureInitialized();

    if(Platform.isIOS) SharedPreferencesIOS.registerWith();
    if(Platform.isAndroid) SharedPreferencesAndroid.registerWith();

    SharedPreferences preferences = await SharedPreferences.getInstance();
    await preferences.reload();

  }`

I think thats the problem come from here : 
    SharedPreferences preferences = await SharedPreferences.getInstance();

Do you have an idea why my silent push action won't work correctly ?

Thank you in advance for you help.

Edit : sorry, it's not a bug. I just need help.

**Comment by rafaelsetragni** [comment]
You need to register manually the plugin on native to use it in any flutter background task. You can check how to do it on the [🍎⁺ Extra iOS Setup for Background Actions topic](https://pub.dev/packages/awesome_notifications#-extra-ios-setup-for-background-actions).

And you need to do the same for awesome_notifications_fcm, but using `SwiftAwesomeNotificationsFcmPlugin` instead of `SwiftAwesomeNotificationsPlugin`.

**Comment by jerdesk** [comment]
Thank you so much ! Now it's working !

**Comment by ffaridi1** [comment]
Hi @rafaelsetragni 
Is this the right code for registering AwesomeNotificationFcm Plugin ?
`GeneratedPluginRegistrant.register(with: self)

            // This function registers the desired plugins to be used within a notification background action
      SwiftAwesomeNotificationsFcmPlugin.setPluginRegistrantCallback { registry in
          SwiftAwesomeNotificationsFcmPlugin.register(
                  with: registry.registrar(forPlugin: "io.flutter.plugins.awesomenotificationsfcm.AwesomeNotificationsFcmPlugin")!)
                FLTSharedPreferencesPlugin.register(
                  with: registry.registrar(forPlugin: "io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin")!)
            }`

Thanks
