### ISSUE TITLE
Android terminated notifications

### ISSUE THREAD

**Issue by vgraphics** [rafaelsetragni/awesome_notifications_fcm#30]
Greetings.

I have completed the implementation as the documentation explains to do so, but I am having problems receiving notifications while app is terminated. Maybe I did not get it `mySilentDataHandle `provide an implementation for receiving background/terminated messages?

**Comment by rafaelsetragni** [comment]
First, `mySilentDataHandle` is target to receive silent pushes, not push notifications. To send silent notifications to android device, you must not use the notification section in your push. And normal notifications vice-versa.

**Comment by vgraphics** [comment]
> First, `mySilentDataHandle` is target to receive silent pushes, not push notifications. To send silent notifications to android device, you must not use the notification section in your push. And normal notifications vice-versa.

Thank you for your answer. Honestly the documentations of firebase for these stuff is very confusing. So what is the proper way to send a background notification? What is the difference between silent notification and simple notification?
