### ISSUE TITLE
LargeIcon is showed correctly on Android but not being showed on iOS

### ISSUE THREAD

**Issue by abdulmalekDery** [rafaelsetragni/awesome_notifications_fcm#32]
I used the same json object in the README.md to send a notification with largeIcon
first I test it on Android and it was showed correctly with the big picture
but when I test it on ios with same json object (for sure after following all of the ios configuration steps) I received the notification and the bigPicture was showed correctly but the largeIcon was not showed as it was showed on Android (default app icon was showed) on   background and foreground and terminated cases.

* What platform did you found the issue 
 iOS

* What devices did you found the issue
 IphoneX

* How are you initializing the plugin
 
 await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await AwesomeNotificationsFcm().initialize(
      onFcmSilentDataHandle: PushNotificationService.mySilentDataHandle,
      onFcmTokenHandle: PushNotificationService.myFcmTokenHandle,
      onNativeTokenHandle: PushNotificationService.myNativeTokenHandle,
      licenseKeys: null,
      debug: kDebugMode);
  AwesomeNotifications().initialize(
      'resource://drawable/small_app_icon',   [
        NotificationChannel(
            channelGroupKey: 'basic_channel_group',
            channelKey: 'basic_channel',
            channelName: 'Basic notifications',
            channelDescription: 'Notification channel for basic notifications',
            defaultColor: AppColors.primaryPurple,
            ledColor: Colors.white),
      ],
      channelGroups: [
        NotificationChannelGroup(
            channelGroupKey: 'basic_channel_group',
            channelGroupName: 'Basic group')
      ],
      debug: kDebugMode
  );

* How are you creating the notification
I let the library doing that

How to make the LargeIcon work on iOS

**Comment by rafaelsetragni** [comment]
Hi @abdulmalekDery, iOS does not have the large icon for NotificationLayout.BigPicture, only for NotificationLayout.Messaging and NotificationLayout.MessagingGroup, but currently is not implemented and its on our roadmap to be released at version 0.7.6.
