### ISSUE TITLE
Notification not clearing on Android

### ISSUE THREAD

**Issue by a1erons** [rafaelsetragni/awesome_notifications_fcm#35]
Everything works fine on iOS, but when you requireInputText* on Android together with the SilentBackgroundAction*, after typing and sending message, the notification keeps popping up again and again and again. #i'm using a samsung device

**Comment by rafaelsetragni** [comment]
Yes, after a notification is replied, it gains a different status where it can only be dismissed by the user. But you can update this notification send another notification with same id
