### ISSUE TITLE
Incompatibility with firebase_core 2.8.0

### ISSUE THREAD

**Issue by Clon1998** [rafaelsetragni/awesome_notifications_fcm#36]
After upgrading my `firebase_core` dependency from `2.7.1` -> `2.8.0` I noticed that my app does not start anymore on IOS devices.

After a lot of hours trying to reproduce the issue using a simulator I noticed the following things:
- It is only reproducible by using a physical device
- It only happens the first time the app is launched via debugging console, subsequent Hot Reloads/Restarts don't throw the same issue/error.

After that I was able to see the following error message in the console: `The operation couldn’t be completed. No APNS token specified before fetching FCM Token (AwesomeExceptionReceiver:54)`

I did some more research and found the same error message on the [react-native-firebase](https://github.com/invertase/react-native-firebase/issues/6893#issuecomment-1421591979) GitHub page.

On the mentioned issue, one of the users also states:
> with the latest firebase-ios-sdk (v10.4.0+) an APNS token is strictly required as a prerequisite to get an FCM token

This also aligns with the changelog of [firebase_core](https://pub.dev/packages/firebase_core/changelog#280) since they updated the Firebase iOS SDK from `10.3.0` to `10.5.0`.

For now, I was able to resolve this bug/issue by downgrading `firebase_core` version to `2.7.1`

Here is more or less the full log of my device:
```log
D/Swift: [AWESOME NOTIFICATIONS] Awesome notifications 10791486656 attached to app instance (AwesomeNotifications:103)
...
D/Swift: [AWESOME NOTIFICATIONS] Awesome Notification's license key validated (AwesomeNotificationsFcm:89)
10.6.0 - [FirebaseMessaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '89780370025'.Be sure to re-retrieve the FCM token once the APNS device token is set.
10.6.0 - [FirebaseMessaging][I-FCM002022] Declining request for FCM Token since no APNS Token specified
E/Swift: [AWESOME NOTIFICATIONS] The operation couldn’t be completed. No APNS token specified before fetching FCM Token (AwesomeExceptionReceiver:54)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FCM_EXCEPTION, The operation couldn’t be completed. No APNS token specified before fetching FCM Token, awesomeFcmException.FcmException.request.token, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      AwesomeNotificationsFcm.requestFirebaseAppToken (package:awesome_notifications_fcm/src/awesome_notifications_fcm_core.dart:128:9)
<asynchronous suspension>
#3      NotificationService.initializeRemoteMessaging (package:mobileraker/service/notification_service.dart:164:5)
<asynchronous suspension>
#4      NotificationService.initialize (package:mobileraker/service/notification_service.dart:75:5)
<asynchronous suspension>
#5      main (package:mobileraker/main.dart:47:3)
<asynchronous suspension>
D/Swift: [AWESOME NOTIFICATIONS] Received a new valid APNs token (AwesomeNotificationsFcm:196)
```

**Comment by Clon1998** [comment]
> Hi @Clon1998 , i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this issue. Please, check it out to see if this issue is solved on these new versions.
> 
> Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.

Thanks for the info. The latest release of Flutter sadly created a TON of incompatibilities between the packages I currently use. Therefore, I can give you feedback once all the packages adjust to the latest version!

**Comment by rafaelsetragni** [comment]
Sure! This was an previous announced changed that many packages ignored. I myself also had to change some of my old projects, replacing packages and etc, because of dart 3 incompatibilities with these packages. But the benefits of migrating overwhelming the effort.

**Comment by Clon1998** [comment]
> Hi @Clon1998 , i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this issue. Please, check it out to see if this issue is solved on these new versions.
> 
> Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.

I can confirm that the issue is resolved. Tested on dev.3
