### ISSUE TITLE
Data don't apply on notification in IOS Devices

### ISSUE THREAD

**Issue by shaharhn** [rafaelsetragni/awesome_notifications_fcm#39]
* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins):
  firebase_core: ^2.1.1
  awesome_notifications: ^0.7.4
  awesome_notifications_fcm:
    path: ../

  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^9.2.0

  http: ^0.13.4
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13

  fluttertoast: ^8.0.3
  numberpicker: ^2.0.1
  giffy_dialog: ^1.8.0

  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# What platform did you found the issue
IOS 15.7.5

# What devices did you found the issue
IPhone 7

# How are you initializing the plugin
I'm using the example.

https://github.com/rafaelsetragni/awesome_notifications_fcm/tree/main/example

```Dart

 static Future<void> initializeRemoteNotifications(
      {required bool debug}) async {
    await Firebase.initializeApp();
    await AwesomeNotificationsFcm().initialize(
        onFcmSilentDataHandle: NotificationController.mySilentDataHandle,
        onFcmTokenHandle: NotificationController.myFcmTokenHandle,
        onNativeTokenHandle: NotificationController.myNativeTokenHandle,
        licenseKeys:
        // On this example app, the app ID / Bundle Id are different
        // for each platform, so was used the main Bundle ID + 1 variation
        [
            // me.carda.awesome-notifications-fcm.example
            'B3J3yxQbzzyz0KmkQR6rDlWB5N68sTWTEMV7k9HcPBroUh4RZ/Og2Fv6Wc/lE'
            '2YaKuVY4FUERlDaSN4WJ0lMiiVoYIRtrwJBX6/fpPCbGNkSGuhrx0Rekk'
            '+yUTQU3C3WCVf2D534rNF3OnYKUjshNgQN8do0KAihTK7n83eUD60=',

            // me.carda.awesome_notifications_fcm.example
            'UzRlt+SJ7XyVgmD1WV+7dDMaRitmKCKOivKaVsNkfAQfQfechRveuKblFnCp4'
            'zifTPgRUGdFmJDiw1R/rfEtTIlZCBgK3Wa8MzUV4dypZZc5wQIIVsiqi0Zhaq'
            'YtTevjLl3/wKvK8fWaEmUxdOJfFihY8FnlrSA48FW94XWIcFY=',
        ],
        debug: debug);
  }

```

# How are you creating the notification
Trying to send from the ui in the example, I do get a notification from the remote with fcm token but without all the handled data.

# The output of `flutter doctor` command

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.9, on macOS 13.3.1 22E261 darwin-arm64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.77.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

```

```Dart
Map<String, dynamic> getFirebaseExampleContent({required String firebaseAppToken}) {
    return {
      'to': firebaseAppToken,
      "mutable-content": true,
      "content_available": true,
      "notification": {
        "title": " ",
      },
      "data" : {
        "content": {
          "id": 100,
          "channelKey": "alerts",
          "title": "Huston! The eagle has landed!",
          "body": "A small step for a man, but a giant leap to Flutter's community!",
          "notificationLayout": "BigPicture",
          "largeIcon": "https://media.fstatic.com/kdNpUx4VBicwDuRBnhBrNmVsaKU=/full-fit-in/290x478/media/artists/avatar/2013/08/neil-i-armstrong_a39978.jpeg",
          "bigPicture": "https://www.dw.com/image/49519617_303.jpg",
          "showWhen": true,
          "autoCancel": true,
          "privacy": "Private",
          "payload": {
            "secret": "Awesome Notifications Rocks!"
          }
        },
        "actionButtons": [
          {
            "key": "REDIRECT",
            "label": "Redirect",
            "autoCancel": true
          },
          {
            "key": "REPLY",
            "label": "Reply",
            "buttonType": "InputField",
            "autoCancel": true
          },
          {
            "key": "DISMISS",
            "label": "Dismiss",
            "autoCancel": true
          }
        ],
        "schedule": {
          "interval": 5,
          "repeats": false
        }
      }
    };
  }
```

# **3 - How To Reproduce the Error**

1. Run 'main_complete'
2. Click on 'Go to Firebase Backend Emulator'
3. Enter your fcm token
4. Send the notification by pressing the button at the bottom called 'Send Firebase request'
5. You will get the notification but without any data

# **4 - Expected behavior**
1. Run 'main_complete'
2. Click on 'Go to Firebase Backend Emulator'
3. Enter your fcm token
4. Send the notification by pressing the button at the bottom called 'Send Firebase request'
5. You will get the notification with all data with picture, action buttons and large icon

----------------------------------

I do see an error at the start:
`(lldb) 2023-05-01 10:17:18.946689+0300 Runner[5307:293374] [User Defaults] Couldn't read values in CFPrefsPlistSource<0x283149280> (Domain: group.awn.105d54d7, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd`

-----------------------------------

I have a server with handles there all the notifications.

I've tried to make a notification with actions and image as we have in the local in the example.

Results:
Android: works perfectly, locally notifications and remote notifications received with all the parameters include image and actions.
IOS: partly works, locally notifications works perfectly, remote notifications doesn't receive any of the data, not actions and not image.

For this try I used your example in backend like as the flutter example.

the local notifications works perfect with the action buttons and image and everything needed, but when I send it from my server through fcm it looks like it doesn't handle all the things under 'data' it happpens only with IOS devices in android the same json work like a charm, this is very helpful plugins and if it will work also for iOS it will be excellent!
Thank for you great job!

![IMG_0469](https://user-images.githubusercontent.com/6049907/235421885-e66c1b0e-7df2-4e2f-987b-843f2a496d9a.PNG)
![IMG_0470](https://user-images.githubusercontent.com/6049907/235421895-ae4030b0-2643-46bf-b99b-31fa3327c002.PNG)
![IMG_0471](https://user-images.githubusercontent.com/6049907/235421908-6f019985-9386-43b1-b995-0599d5624dd0.PNG)

**Comment by guyluz11** [comment]
You need to remove  "content_available" as it conflicts with  "mutable-content"

This is a fix for your issue, the example had incorrect data
https://github.com/rafaelsetragni/awesome_notifications_fcm/issues/40
