### ISSUE TITLE
Example firebase_datasource file possible conflicting settings

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications_fcm#40]
It is stated in the readme that fcm data should not contain "content_available" and "mutable_content" at the same time

> To send silent push notifications, you must not use "notification" section and you need to use "content_available" instead of "mutable_content"

But in the example file named `firebase_datasource.dart` there is the use of both one after another

https://github.com/rafaelsetragni/awesome_notifications_fcm/blob/7e4aabb88024c42a2069e6db719682d07e6c3021/example/lib/datasources/firebase_datasource.dart#L66
Next line
https://github.com/rafaelsetragni/awesome_notifications_fcm/blob/7e4aabb88024c42a2069e6db719682d07e6c3021/example/lib/datasources/firebase_datasource.dart#L67

Can they conflict with each other?

**Comment by guyluz11** [comment]
If it is irrelevant to the current version, it needs to be removed, I have an open pr that removes this line, or you can do it yourself but either way, it is a misleading example.

**Comment by rafaelsetragni** [comment]
I built this page to help everyone without a backend or postman available to send real push notifications to test. It still valid and its a good idea to update.
