### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mazab99** [rafaelsetragni/awesome_notifications_fcm#44]
awesome_notifications_fcm-0.7.4+1/lib/src/models/fcm_silent_data.dart:32:57: Error: Too many positional arguments: 2 allowed, but 3 found.
Try removing the extra positional arguments.
          _createdDate = AwesomeAssertUtils.extractValue(
                                                        ^
/Users/mahmoudazab/.pub-cache/hosted/pub.dev/awesome_notifications-0.7.5-dev.2+1/lib/src/utils/assert_utils.dart:55:10: Context: Found this candidate, but the arguments don't match.
  static extractValue<T>(String reference, Map dataMap) {
         ^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

**Comment by mazab99** [comment]
awesome_notifications_fcm: ^0.7.4+1
  awesome_notifications: ^0.7.4+1

**Comment by Fathi123-max** [comment]
Hello, Sir, I have Faced This Bug 
and the  Solution for me was to upgrade to the dev Version 

  awesome_notifications_fcm: ^0.7.5-dev.3
  awesome_notifications: ^0.7.5-dev.3   

alhamedlleah app run again
