### ISSUE TITLE
Packge add's AD_ID android permission

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications_fcm#46]
# Rules

## **1 - Describe the bug**

Adding the package adds `com.google.android.gms.permission.AD_ID` permission to the app which makes the PlayStore consider my app as using Advertisements. 

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant information, such as:

* Your plugins list inside the file `pubspec.yaml` :  `awesome_notifications_fcm: ^0.7.4+1`
* What platform did you found the issue: Android

## **3 - How To Reproduce the Error**

Here is how I checked that the `com.google.android.gms.permission.AD_ID` permission came from this package.
1. Create appbundle file from app that includes awesome_notifications_fcm permission `flutter build appbundle --release`
2. Change the created appbundle `.aab` file ending to .zip
3. Navigate inside the zip to the following file and open it in a text editor .zip\base\manifest\AndroidManifest
4. Search for the text `com.google.android.gms.permission.AD_ID` and it will find a result.
5. Now repeat the same process after removing `awesome_notifications_fcm` from the app packages and you will see that `com.google.android.gms.permission.AD_ID` can't be found.

## **4 - Expected behavior**
The notification package should not add advertising permissions to my app.

## **6 - Additional context**
In android permission system there is a way to force remove permission like this
`<uses-permission android:name="com.google.android.gms.permission.AD_ID" tools:node="remove"/>`.
I am not sure if it will hurt the package functionality, didn't test it yet.

**Comment by rafaelsetragni** [comment]
There is no permission.AD_ID declared in any AndroidManifest in the core libraries or flutter libraries. If you have found where it is located, please point it out to me here and I will remove it.

I can't put the command `<uses-permission android:name="com.google.android.gms.permission.AD_ID" tools:node="remove"/>.` because that might remove permission for apps that in fact need to use such permission.

**Comment by rafaelsetragni** [comment]
In fact, there is no `permission.AD_ID` in awesome, but it is in Firebase libraries, specially analytics. Im trying to figure out how to remove it, but i couldn't yet.

**Comment by guyluz11** [comment]
In the meantime can write about it in the documentation/readme
