### ISSUE TITLE
Confusing documentation about receiving notifications in terminated state.

### ISSUE THREAD

**Issue by Tristannos** [rafaelsetragni/awesome_notifications_fcm#56]
I read the documentation and I saw this line:

> App Termination: Note that if your app is forcibly closed on any platform, all subsequent notifications will not be delivered until your app is actively reopened.

Well,  so does that mean if you app is terminated, you don't receive any notifications? 
How does that work? Isn't a notification something to alert the user that they need to open the application, because there is something to do or alert?

**Comment by 10ndavis** [comment]
https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application#discussion

From my understanding, this is a limitation on iOS.

"However, the system does not automatically launch your app if the user has force-quit it. In that situation, the user must relaunch your app or restart the device before the system attempts to launch your app automatically again."
