### ISSUE TITLE
Cocoapods AwesomePodFile file: cannot load

### ISSUE THREAD

**Issue by ObranS** [rafaelsetragni/awesome_notifications_fcm#63]
*Reproducing Plugin version:*
  awesome_notifications_core: ^0.9.1
  awesome_notifications: any

When the **_pod install_** cocoapods show the issue: _[!] Invalid `Podfile` file: cannot load such file -- ../ios/.symlinks/plugins/awesome_notifications/ios/Scripts/AwesomePodFile._

Checked the path and found out that there located: AwesomeFcmPodFile.rb only:

<img width="399" alt="Screenshot 2024-02-01 at 13 30 11" src="https://github.com/rafaelsetragni/awesome_notifications_fcm/assets/5585509/76dc6f8d-6f41-4a93-b1f9-16352ebb46c1">

**Comment by rafaelsetragni** [comment]
Your files are not matching the plugin version. Clean your cache with `flutter pub cache clean` set all plugins to the latest version and execute `pub get` again

**Comment by ObranS** [comment]
Yes, this helped. Not sure why it happened so before. But after `flutter pub cache clean` and `pub get` work!

**Comment by ObranS** [comment]
Owner answered how to solve this issue
