### ISSUE TITLE
How to call (legacy) FirebaseMessaging.onBackgroundMessage / (now) mySilentDataHandle

### ISSUE THREAD

**Issue by TomasWard1** [rafaelsetragni/awesome_notifications_fcm#8]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

I have recently migrated from `firebase_messaging` to` awesome_notifications_fcm 0.7.4+1` and I am not able to handle a Data Only notification sent successfully through fcm post request.

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

Only notification plugins are `awesome_notifications_fcm` and `awesome_notifications`
Issue found on android 
Device error: Pixel 4
I am initializing the plugin in the `main.dart` file as so:

```Dart
AwesomeNotifications().initialize(
      null,
      [
        NotificationChannel(
            channelGroupKey: 'basic_channel_group',
            importance: NotificationImportance.Max,
            channelKey: 'basic_channel',
            channelName: 'Basic notifications',
            channelDescription: 'Main channel.',
            defaultColor: Color(0xFF9D50DD),
            ledColor: Colors.white)
      ],
      channelGroups: [
        NotificationChannelGroup(channelGroupKey: 'basic_channel_group', channelGroupName: 'Basic group')
      ],
      debug: false);

    await AwesomeNotificationsFcm().initialize(
        onFcmSilentDataHandle: mySilentDataHandle,
        onFcmTokenHandle: myFcmTokenHandle,
        onNativeTokenHandle: myNativeTokenHandle,
        licenseKeys: null,
        debug: debug);
```

Every Handle has a print statement to see if it is called. None are ever called. The FCM post request is sent and received succesfully because of these logs in the receiving end:

```
D/Android: [Awesome Notifications](17165): A new Awesome FCM service has started (AwesomeFcmService:46)
D/Android: [Awesome Notifications](17165): received a new fcm push (id: 0:1667266897892216%a2b2f303f9fd7ecd) (AwesomeFcmService:134)
D/Android: [Awesome Notifications](17165): New silent push received (FcmInterpreter:217)
D/Android: [Awesome Notifications](17165): A new silent background service has started (FcmSilentService:23)
I/Android: [Awesome Notifications](17165): Initializing Flutter global instance. (FcmDartBackgroundExec:144)
I/Android: [Awesome Notifications](17165): Creating background FlutterEngine instance. (FcmDartBackgroundExec:157)
W/MediaSessionCompat(17165): Couldn't find a unique registered media button receiver in the given context.
D/Android: [Awesome Notifications](17165): Awesome Notifications plugin attached to Android 33 (AwesomeNotificationsPlugin:155)
D/Android: [Awesome Notifications](17165): Awesome Notifications attached to engine for Android 33 (AwesomeNotificationsPlugin:137)
D/Android: [Awesome Notifications](17165):  subscribed to receive FCM events (AwesomeFcmEventsReceiver:51)
D/Android: [Awesome Notifications](17165):  subscribed to receive FCM events (AwesomeFcmEventsReceiver:71)
I/Android: [Awesome Notifications](17165): Executing background FlutterEngine instance for silent FCM. (FcmDartBackgroundExec:180)
I/Android: [Awesome Notifications](17165): All silent data fetched. (FcmDartBackgroundExec:249)
I/Android: [Awesome Notifications](17165): Shutting down background FlutterEngine instance. (FcmDartBackgroundExec:208)
D/Android: [Awesome Notifications](17165): Awesome Notifications plugin detached from Android 33 (AwesomeNotificationsPlugin:180)
D/Android: [Awesome Notifications](17165):  unsubscribed from notification events (AwesomeFcmEventsReceiver:59)
D/Android: [Awesome Notifications](17165):  unsubscribed from notification events (AwesomeFcmEventsReceiver:79)
I/Android: [Awesome Notifications](17165): FlutterEngine instance terminated. (FcmDartBackgroundExec:215)
I/TRuntime.CctTransportBackend(17165): Making request to: https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog
I/TRuntime.CctTransportBackend(17165): Status Code: 200
```

## **3 - How To Reproduce the Error**

Initialize as shown and sent a post request like this:

```Dart
 "to": fcmToken,
    "content_available": true,
    "content-available":true,
    //"apns-priority": 5,
    "priority": "high",
    "data": {
      'title': title,
      'body': body,
      'image_url': imageUrl,
      'sender_id': globalCurrentUserID,
      if (date != null) 'date': date.toString(),
      if (itemId != null) 'item_id': itemId,
      if (itemTitle != null) 'item_title': itemTitle,
      if (groupId != null) 'group_id': groupId
    },
```

## **4 - Expected behavior**
I expect for any handler to be called when data only messages arrive (in the foreground and background). So that I can use the ReceivedNotification object for my app logic.

## **5 - Screenshots**
No Screenshots

## **6 - Additional context**
It would be ideal if you found something that I setup wrong. If not, could you provide me with the appropriate places where I need to place my initialization or how to call/listen to the handlers? THANK YOU!

**Comment by rafaelsetragni** [comment]
```Json
 "to": fcmToken,
    "content_available": true,
    "content-available":true,
    //"apns-priority": 5,
    "priority": "high",
    "data": {
      'title': title,
      'body': body,
      'image_url': imageUrl,
      'sender_id': globalCurrentUserID,
      if (date != null) 'date': date.toString(),
      if (itemId != null) 'item_id': itemId,
      if (itemTitle != null) 'item_title': itemTitle,
      if (groupId != null) 'group_id': groupId
    },
```

There is some misconceptions about your payload. You're sending a silent push notification, but in your payload there is  title, body and image_url, which are from notification section. And you are using  "content_available" and "content-available" at same time, indicating a confusion about which firebase messaging version are you working on.

So, first things first, describe to me what is your main goal:

- Do you wanna display a notification to the user or execute some background task sent by your server side? 
- How are you creating your push notifications on your server side?

**Comment by TomasWard1** [comment]
Thanks for the response! @rafaelsetragni 
**Main goal:** Think of this situation (I am working on this now): There is a chat in my app, and I want for every chat to be accompanied by a notification to the user. I am using FCM because a user can have multiple devices (therefore multiple fcm tokens) & because there are chat groups where one message needs to trigger a notification send to multiple devices.



**Step 2** 
Now, when I have received the FCM silent data/only notification, I want to trigger a messageReceived() handler that sends an Awesome Push Notification to the device. This can happen to multiple users at once, for example, in a group chat.

**Flow**: FCM message ==> message received on device ==> push notification sent.
My understanding is that this can only be achieved with FCM silent notifications.

To answer some of your remarks:

> but in your payload there is title, body and image_url, which are from notification section.
Yes, this is because I pass that data in the messageReceived() handler to the actual push notification that has to be sent. 

**Why do I not use a notification section directly in the payload?**  
This is because I have to send scheduled notifications. That can only be done with silent FCM messages that have some schedule data in them, which then schedules the push notification.

**How are you creating your push notifications on your server side?**
The creation of push notifications is actually handled when the FCM message gets to the device.

### Follow up remarks

1.  Do you think that instant notifications, like a chat send, should have a payload with a notification section? And then the scheduled ones should be data only? Or which is the best practice?
2. I am using GetX, I thought this may be a useful remark. This means that most of my screens are GetViews or Statless Widgets.
3. I used  "content_available" and "content-available" both because I did not know which version to use. I will then stay with the lates which is "content-available.


I hope this helps. Kindly, Tomas.

**Comment by rafaelsetragni** [comment]
I think the best approach for you is to not use silent push notifications to display notifications to the user. Instead you gonna send a normal notification with `displayOnForeground` set to `false`. Then you gonna implement the static handler `onNotificationCreatedMethod` to decide if the notification must be displayed or not. If the notification was displayed in foreground and the user isn't at the moment in the chat conversation, you gonna create the respective local notification. Otherwise you can ignore the event.

> Why do I not use a notification section directly in the payload?

This is not a good approach. If you call background tasks too often the device may starts to block your app to execute any background tasks.

> 1- Do you think that instant notifications, like a chat send, should have a payload with a notification section? And then the scheduled ones should be data only? Or which is the best practice?

Yes, but the notification itself already contains all the notification data to be recreated. I don't know your app demands, but i guess you don't need to replicate it in payload data. To schedules i recommend you to use the silent data, but with caution.

> 2- I am using GetX, I thought this may be a useful remark. This means that most of my screens are GetViews or Statless Widgets.

Awesome is totally compatible with any state manager plugin. I use GetX in my current projects.

> 3 - I used "content_available" and "content-available" both because I did not know which version to use. I will then stay with the lates which is "content-available.

If you are using the legacy Firebase version, you need to use content_available. If you're using the newest V1, you need to use content-available. To display custom notifications you need to use mutable_content or mutable-content instead.

**Comment by TomasWard1** [comment]
Okay, thank you. however the problem is not solved. Using the json data that is provided in the example of the plugin, my FCMSilentDataHandle is never called. I even get this message but no handler is called. Is there a specific place to initialize it?

`D/Android: [Awesome Notifications](  312): received a new fcm push (id: 0:1668284909536342%a2b2f303f9fd7ecd) (AwesomeFcmService:134)`

**Comment by rafaelsetragni** [comment]
But with this json payload your onFcmSilentDataHandle will never get called. You must not use notification section and use content_available instead of mutable_content. This json data is for alert push notification, which displays normal notifications to the user.

**Comment by TomasWard1** [comment]
Okay, thanks for the clarification. So, with that json data, `onNotificationCreatedMethod` should be called when receiving a fcm message - but it doesn't get called. It should also show a notification to the user, but it doesn't. What am I missing?

**Comment by rafaelsetragni** [comment]
Take a look at this topic to know where all the events will be called in your app life cycle:
https://pub.dev/packages/awesome_notifications#-notification-events

**Comment by irjayjay** [comment]
@rafaelsetragni, you mention that with @TomasWard1's payload the onFcmSilentDataHandle will never get called, why is this? The payload does include the required content_available flag and the data object. 

It should not matter whether the keys in the data object have "title", "body", "image_url" in them, what you add as data to a data notification should be inconsequential.

Our app is in a similar boat where we used to register our handler with FirebaseMessaging.onBackgroundMessage and it worked perfectly fine, but now registering it with the onFcmSilentDataHandle we get the same logs as @TomasWard1.

Here's our payload:
```
{
    "content_available": true,
    "priority": "high",
    "data": {
        "alert_id": "ABCD",
        "click_action": "FLUTTER_NOTIFICATION_CLICK",
        "createdDate": "2022-11-15 14:03:17.000Z",
        "createdLifeCycle": "Foreground",
        "createdSource": "Firebase",
        "created_time": "2022-11-15T14:03:01Z",
        "id": null,
    }
}
```

**Comment by rafaelsetragni** [comment]
> @rafaelsetragni, you mention that with @TomasWard1's payload the onFcmSilentDataHandle will never get called, why is this? The payload does include the required content_available flag and the data object.
> 
> It should not matter whether the keys in the data object have "title", "body", "image_url" in them, what you add as data to a data notification should be inconsequential.

But it matters. If you put notification section with at least title and body not empty, the notification servers will identify your notification as a visual notification and will delivery them with more priority. Otherwise, they will flag your push notification as a silent push and will delivery it with low priority and will execute it with as a background task.
 
Visual notifications can have a higher priority exactly because they do not execute background tasks when called. These silent background handles are designed to run as background tasks.

> Our app is in a similar boat where we used to register our handler with FirebaseMessaging.onBackgroundMessage and it worked perfectly fine, but now registering it with the onFcmSilentDataHandle we get the same logs as @TomasWard1.
> 
> Here's our payload:
> 
> ```
> {
>     "content_available": true,
>     "priority": "high",
>     "data": {
>         "alert_id": "ABCD",
>         "click_action": "FLUTTER_NOTIFICATION_CLICK",
>         "createdDate": "2022-11-15 14:03:17.000Z",
>         "createdLifeCycle": "Foreground",
>         "createdSource": "Firebase",
>         "created_time": "2022-11-15T14:03:01Z",
>         "id": null,
>     }
> }
> ```

Yes, your payload is in fact a silent push notification, and its all looking good. Maybe you're sending it using firebase libraries in your server, and these libraries now are using the firebase V1 and not the legacy one. Firebase legacy protocol uses `content_available` and Firebase V1 protocol uses `content-available`.

But on @TomasWard1 case, he was sending a normal visual notification expecting to call the silent handle method. Silent push notifications and Alert notifications are different things for different purposes.

**Comment by TomasWard1** [comment]
Thank you @irjayjay , I knew someone else was having this problem. I too used `FirebaseMessaging.onBackgroundMessage` before and it worked. Now, I cannot handle data-only fcm messages. Nor do notifications get called when I add a notification section in the JSON.

@rafaelsetragni you keep mentioning firebase V1 and the legacy protocol. But I really do not know what that means nor how to implement it. I have tried using 'content-available' and 'content_available', and none of them work. I have even tried the tested JSON on your documentation and it doesn't work.

On the other hand, what I mentioned in the last comment, I tried sending a notification message with the notification present in the JSON data [it is the one from your documentation] and:

1. I did not receive a notification in the device. (It should be called if the notification part is present in the JSON)
2. No handler was called.

I am sending the fcm message from an android Pixel 4 simulator and receiving it on a real Pixel 4 physical device.

There is a clear problem between the connection of FCM messages and the notification handlers. It may be on our part or it may be the plugin. Can you replicate the behavior we are telling you @rafaelsetragni ? 

@irjayjay if you send the JSON with the notification section, does a push notification get sent? does a handler get called?

Thank you all.

**Comment by rafaelsetragni** [comment]
> Thank you @irjayjay , I knew someone else was having this problem. I too used `FirebaseMessaging.onBackgroundMessage` before and it worked. Now, I cannot handle data-only fcm messages. Nor do notifications get called when I add a notification section in the JSON.
> 
> @rafaelsetragni you keep mentioning firebase V1 and the legacy protocol. But I really do not know what that means nor how to implement it. I have tried using 'content-available' and 'content_available', and none of them work. I have even tried the tested JSON on your documentation and it doesn't work.

Take a look at this documentation to see what is Legacy and V1 protocols:
https://firebase.google.com/docs/cloud-messaging/migrate-v1

> On the other hand, what I mentioned in the last comment, I tried sending a notification message with the notification present in the JSON data [it is the one from your documentation] and:
> 
> 1. I did not receive a notification in the device. (It should be called if the notification part is present in the JSON)
> 2. No handler was called.

If nothing happens can be your google-info.plist or google-services.json that are not matching your app nor in the right place. But if it everything configured correctly in your server and you send a most basic notification, like:

```Json
{
    "to": fcmToken,
    "priority": "high",
    "mutable_content": true,
    "notification": {
      "badge": 42,
      "title": "title",
      "body": "body"
    }
}
```

...it MUST display a simple notification. And you can do the same test using Firebase console:

![image](https://user-images.githubusercontent.com/40064496/201962920-a47c7fbb-70f4-4552-a854-095f113eaed4.png)

> I am sending the fcm message from an android Pixel 4 simulator and receiving it on a real Pixel 4 physical device.
> 
> There is a clear problem between the connection of FCM messages and the notification handlers. It may be on our part or it may be the plugin. Can you replicate the behavior we are telling you @rafaelsetragni ?
> 
> @irjayjay if you send the JSON with the notification section, does a push notification get sent? does a handler get called?
> 
> Thank you all.

Guys, just to confirm: are you checking if your silent push notifications are getting called and running using LogCat or Console.app, right? Because this is a silent push notification, and its silent and will not display anything on the screen. So, you need to check the device logs to get it.

In any case, take these log messages and put them here to be analyzed.

**Comment by TomasWard1** [comment]
Everything has been fixed. Thanks for all your help. Here is how I solved it:
- I tested with the firebase console and the notification got to my phone. So a problem with the connection between firebase and my app got discarded.
- Then I printed the fcm json data that was being sent and realized it was not what I had modified.
- I then realized that I was debugging a JSON data that was actually not being sent, it was calling another function.
- So I modified and tested the actual JSON data and all the handlers are called: Both with the silent fcm messages and the notification fcm messages.

My bad. Thanks for the help though, I am sure this conversation will be useful to others.

**Comment by rafaelsetragni** [comment]
I will let this issue open so it's easier to others find it.

**Comment by lorenzorheinicke** [comment]
> Guys, just to confirm: are you checking if your silent push notifications are getting called and running using LogCat or Console.app, right? Because this is a silent push notification, and its silent and will not display anything on the screen. So, you need to check the device logs to get it.
> 
> In any case, take these log messages and put them here to be analyzed.

@rafaelsetragni I'm working with @irjayjay on this issue. the only logs (logcat and VSCode logs) that we can see coming in are the following:
```
D/Android: [Awesome Notifications](13811): A new Awesome FCM service has started (AwesomeFcmService:46)
D/Android: [Awesome Notifications](13811): received a new fcm push (id: 0:1668591989599295%13eec418f9fd7ecd) (AwesomeFcmService:134)
D/Android: [Awesome Notifications](13811): New silent push received (FcmInterpreter:217)
```

This tells me the device is getting the silent notification, when our app is in the background. 

When we send the same notification, while the app is in the foreground, we can get the `onFcmSilentDataHandle` listener to trigger. 

Just to re-confirm this is the notification payload that we are sending:
```
{
    "content_available": true,
    "priority": "high",
    "data": {
        "alert_id": "ABCD",
        "click_action": "FLUTTER_NOTIFICATION_CLICK",
        "createdDate": "2022-11-15 14:03:17.000Z",
        "createdLifeCycle": "Foreground",
        "createdSource": "Firebase",
        "created_time": "2022-11-15T14:03:01Z",
        "id": null,
    }
}
```

**Comment by kschrage** [comment]
I'm also struggling to get `mySilentDataHandle` called at least on iOS. I can get visible notifications to display without a problem and the `myActionReceivedMethod` is called, if a tap on the notification.

FCM-Payload (V1-API) is as follows:
```
{
  "message": {
    "token": "...",
    "data": {
      "order_id": "123123"
    },
    "apns": {
    	"headers": {
    		"apns-push-type": "background",
    		"apns-priority": "5"
    	},
      "payload": {
        "aps": {
        	"content-available": 1,
        	"sound": ""
        }
      }
    }
  }
}
```
From the console.app I can see the following telling me: app is invoked to process my push-message:
```
standard	14:11:13.820704+0100	SpringBoard	[myapp] Received remote notification request AEBA-EF36 [ waking: 0, hasAlertContent: 0, hasSound: 0 hasBadge: 0 hasContentAvailable: 1 hasMutableContent: 0 pushType: Background]
standard	14:11:13.820864+0100	SpringBoard	[myapp] Process delivery of push notification AEBA-EF36
standard	14:11:13.821016+0100	SpringBoard	[myapp] Request DUET delivers content-available push notification to application
standard	14:11:13.821155+0100	SpringBoard	SUBMITTING: com.apple.pushLaunch.myapp:ADC65E
standard	14:11:13.821840+0100	dasd	Submitted Activity: com.apple.pushLaunch.myapp:ADC65E at priority 5 <private>
standard	14:11:13.826685+0100	dasd	com.apple.pushLaunch.myapp:ADC65E:[
	{name: ApplicationPolicy, policyWeight: 50.000, response: {Decision: Absolutely Must Proceed, Score: 1.00, Rationale: [{[appIsForeground]: Required:1.00, Observed:1.00},]}}
 ], FinalDecision: Absolutely Must Proceed}
standard	14:11:13.827864+0100	dasd	[FBSSystemService][0xf9cd] Sending request to open "myapp"
standard	14:11:13.828617+0100	SpringBoard	[FBSystemService][0xf9cd] Received request to open "myapp" from dasd:101.
standard	14:11:13.829313+0100	SpringBoard	Received trusted open application request for "myapp" from <FBProcess: 0x11388d550; daemon<com.apple.dasd>:101(v13D)>.
standard	14:11:13.856034+0100	SpringBoard	Executing request: <SBMainWorkspaceTransitionRequest: 0x2831bba80; eventLabel: OpenApplication(sceneID:myapp-default)ForRequester(dasd.101); display: Main; source: FBSystemService>
standard	14:11:13.856260+0100	SpringBoard	Executing suspended-activation immediately: OpenApplication(sceneID:myapp-default)ForRequester(dasd.101)
standard	14:11:13.856316+0100	SpringBoard	[FBWorkspaceEvent] Executing: <FBWorkspaceEvent: 0x2803009c0; OpenApplication(sceneID:myapp-default)ForRequester(dasd.101)>
standard	14:11:13.856425+0100	SpringBoard	[FBWorkspaceEvent] Executing: <FBWorkspaceEvent: 0x2803a7760; OpenApplication(sceneID:myapp-default)ForRequester(dasd.101)>
standard	14:11:13.874653+0100	Runner	sceneOfRecord: sceneID: sceneID:myapp-default  persistentID: C1392DCC-9D8B-4268-B4F9-2C9C6F322A53
standard	14:11:13.876192+0100	runningboardd	Acquiring assertion targeting [application<myapp>:8834] from originator [daemon<com.apple.dasd>:101] with description <RBSAssertionDescriptor| "com.apple.das.backgroundFetch" ID:33-101-17464 target:8834 attributes:[
	<RBSDomainAttribute| domain:"com.apple.dasd" name:"BackgroundDownload" sourceEnvironment:"(null)">
	]>
standard	14:11:13.876326+0100	runningboardd	Assertion 33-101-17464 (target:[application<myapp>:8834]) will be created as active
standard	14:11:13.880186+0100	runningboardd	Calculated state for application<myapp>: running-active (role: UserInteractiveFocal)
standard	14:11:14.053349+0100	symptomsd	SymptomAnalytics ServiceImpl: FAE perform query for dasd (pid 101) on LiveUsage predicate hasProcess.bundleName == $targetname sort (null) actions {
    "<null>" = "<null>";
    refreshUsage = refreshUsage;
    "hasProcess.firstTimeStamp" = copyRelationship;
    "hasProcess.bundleName" = copyRelationship;
    nameChain = "myapp";
    "hasProcess.procName" = copyRelationship;
} properties (null)
standard	14:11:14.913422+0100	symptomsd	entry: Sat Dec  3 14:41:26 2022                  myapp (bundle)        486758       138217            0            0   0   1
standard	14:11:14.920223+0100	runningboardd	Invalidating assertion 33-101-17464 (target:[application<myapp>:8834]) from originator [daemon<com.apple.dasd>:101]
standard	14:11:14.923413+0100	symptomsd	SymptomAnalytics ServiceImpl: FAE perform query for dasd (pid 101) on LiveUsage predicate hasProcess.bundleName == $targetname sort (null) actions {
    "<null>" = "<null>";
    refreshUsage = refreshUsage;
    "hasProcess.firstTimeStamp" = copyRelationship;
    "hasProcess.bundleName" = copyRelationship;
    nameChain = "myapp";
    "hasProcess.procName" = copyRelationship;
} properties (null)
standard	14:11:14.944259+0100	symptomsd	entry: Sat Dec  3 14:41:26 2022                  myapp (bundle)        486758       138217            0            0   0   1
standard	14:11:14.953862+0100	SpringBoard	STARTING: com.apple.pushLaunch.myapp:ADC65E
standard	14:11:14.956146+0100	dasd	COMPLETED com.apple.pushLaunch.myapp:ADC65E at priority 5 <private>!
standard	14:11:14.956554+0100	dasd	NO LONGER RUNNING com.apple.pushLaunch.myapp:ADC65E ...Tasks running in group [com.apple.dasd.defaultNetwork] are 1!
```

Any help appreciated.

Thanks
Klemens

**Comment by awaik** [comment]
Hi!
In my case with the payload
```
{
    "content_available": true,
    "priority": "high",
    "data": {
        some_data
    }
}
```

I got a error

```
dnssd_clientstub write_all(16) DEFUNCT
dnssd_clientstub deliver_request ERROR: write_all(16, 78 bytes) failed
dnssd_clientstub write_all(16) DEFUNCT
```
