### ISSUE TITLE
cloud_functions incompability

### ISSUE THREAD

**Issue by proczak1** [rafaelsetragni/awesome_notifications_fcm#9]
After adding cloud_functions ^4.0.3 i get an error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver found in modules jetified-firebase-iid-20.0.1-runtime (com.google.firebase:firebase-iid:20.0.1) and jetified-firebase-messaging-23.1.0-runtime (com.google.firebase:firebase-messaging:23.1.0)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1

Using:
  awesome_notifications: ^0.7.4+1
  awesome_notifications_fcm: ^0.7.4+1

**Comment by rafaelsetragni** [comment]
There is a conflict in the last firebase bom dependency between firebase-messaging library and cloud-functions library. To solve it you gonna need to use the confictResolver from Gradle.

In you `build.gradle` file (app level), insert these lines:
![image](https://user-images.githubusercontent.com/40064496/199990094-f0ba8072-c208-44c5-9e00-e56a091bdd44.png)

Here are the lines to copy from:
```Ruby
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.name == 'firebase-iid') {
            details.useVersion('21.1.0')
        }
    }
}
```

**Comment by proczak1** [comment]
Okay. Thank you very much Boss :)
